Add support for nlmsg extended permission
SELinuxProject/setools pull request #138
Opened 2024-10-22 02:54 UTC by tweksteen

2024-10-22 18:32 UTC, pebenito commented
you'll need to at least update th github action to use main, so the builds will work. Also you should look at the tests and add some nlmsg examples to prove that this works.

2024-10-23 00:19 UTC, tweksteen commented
Thanks for the review.

I changed the default SELinux branch in the github action as you suggested. I assume this implies that setools will require SELinux >= 3.8 in the future. Is that ok?

There is also a commit to rename IoctlSet to XpermSet. I don't know the compatibility guarantee for the setools API, but its worth mentioning. (This commit is not strictly necessary, but it helps clarifying the role of the class).

I added a test in `test_terulequery.py`. I don't know what's the best place otherwise. Please let me know and I can relocate it or add further tests. Also, I came across the issue that the tests in `TERuleQueryXperm` weren't being executed (as the test class does not starts with "Test"). This is fixed in the commit as well.

2024-10-23 12:49 UTC, pebenito commented
> Thanks for the review.
> 
> I changed the default SELinux branch in the github action as you suggested. I assume this implies that setools will require SELinux >= 3.8 in the future. Is that ok?

That's fine. SETools needs to keep up with new SELinux features.


> There is also a commit to rename IoctlSet to XpermSet. I don't know the compatibility guarantee for the setools API, but its worth mentioning. (This commit is not strictly necessary, but it helps clarifying the role of the class).

SETools only has best-effort compat guarantees. This rename should be ok, but we should probably have a `IoctlSet` class that inherits `XpermSet` and throws a deprecation warning in its `__init__` before calling `super().__init__`.


> I added a test in `test_terulequery.py`. I don't know what's the best place otherwise. Please let me know and I can relocate it or add further tests.

I'd add one test in `tests/library/policyrep/test_rules.py`.

Then in `tests/library/policyrep/selinuxpolicyy.conf` replace one of each of the xperm rule types (allowxperm, auditallowxperm, etc.) to make sure this counts towards the rule counts. Don't add rules, as I intentionally made the rule counts prime numbers.


> Also, I came across the issue that the tests in `TERuleQueryXperm` weren't being executed (as the test class does not starts with "Test"). This is fixed in the commit as well.

Thanks!

2024-10-28 17:40 UTC, pebenito commented
Looks like your build issues are due to issues I've since fixed in #139. You should also rebase to get those fixes.

2024-10-29 03:16 UTC, tweksteen commented
Done. Let me know your thoughts. Thanks.

2024-10-30 12:53 UTC, pebenito requested changes

2024-10-30 12:53 UTC, pebenito commented on setools/policyrep/terule.pxi
> +            return super(XpermSet, self).__format__(spec)
PR looks good, one last nit. `return super().__format__(spec)

2024-11-01 03:33 UTC, tweksteen commented on setools/policyrep/terule.pxi
> +            return super(XpermSet, self).__format__(spec)
Done

2024-11-01 03:34 UTC, tweksteen commented on setools/policyrep/terule.pxi
> +        super().__init__()
Done

2024-11-06 18:48 UTC, pebenito approved these changes

2024-11-06 18:49 UTC, merged

2024-11-06 18:49 UTC, pebenito commented
thanks!